### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [scottlarkin/Reversi---Monte-Carlo-Tree-Search-AI#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by suprafun** [comment]
Sorry to bother you. Just wanted to bump this. Thanks.

**Comment by scottlarkin** [comment]
Hey appologies for the late response, I've not been keeping an eye on git notifications. Just added an Apache V2 license to the project. Feel free to use for any learning purposes. I wouldn't recommend copying the code and using it as-is, but if you can learn from it that's great. This was written years ago in a bit of a hurry, so I can't guarantee that it's bug free or a fully correct monte-carlo tree search, although it certainly worked for my purposes.
